server:
  error:
    include-stacktrace: on-param
  port: 8080
spring:
  application:
    name: pweb_project
  datasource:
    url: jdbc:mysql://localhost:3306/proveskill_db?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
