version: "3.8"


services:
  mysql-service:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - database_data:/var/lib/mysql

  spring-service:
    depends_on:
      - mysql-service
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_DOCKER_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysql-service:$MYSQL_PORT/$MYSQL_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.hibernate.ddl-auto"  : "update",
        "spring.jpa.show-sql" : "true",
        "spring.jpa.generate-ddl" : "true",
        "application.security.jwt.secret-key": "7A244326452948404D635166546A576E5A7234753778214125442A472D4A614E",
        "application.security.jwt.expiration": "86400000",
        "application.security.jwt.refresh-token.expiration": "604800000"
      }'
    stdin_open: true
    tty: true

volumes:
  database_data:
